# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "dry-container", "~> 0.9.0"
gem "active_operation", "~> 1.0"
